import "~/styles/globals.css";
import '@mantine/core/styles.css';

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { AppShell, AppShellHeader, AppShellMain, ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "./_theme";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={GeistSans.className}>
        <MantineProvider theme={theme}>
          <TRPCReactProvider>
            <AppShell
              header={{ height: 60 }}
            >
              <AppShellHeader>
                <Link href="/">MadPrints</Link>
              </AppShellHeader>
              <AppShellMain>
                {children}
              </AppShellMain>
            </AppShell>
          </TRPCReactProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
